site_name: FastTower
site_description: FastTower framework, Django-like framework based on FastAPI
repo_name: FastTower
repo_url: https://github.com/pysashapy/fasttower
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    repo: fontawesome/brands/github-alt

plugins:
  # Material for MkDocs
  search:
  mkdocstrings:
    handlers:
      python:
        options:
          extensions:
            - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          preload_modules:
            - httpx
            - starlette
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
            - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

nav:
  - Home: index.md
  - Quick Start:
      - О проекте: quick/index.md
      - Project Setup: quick/project-setup.md
      - App Setup: quick/app-setup.md
      - Overview: quick/overview.md
  - Advanced Usage:
      - Installation: usage/install.md
      - Admin Panel: usage/admin-panel.md
      - Caching: usage/cache.md
      - Commands: usage/commands.md
      - Email: usage/email.md
      - Models: usage/model.md
      - Routers: usage/routers.md

markdown_extensions:
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  # Python Markdown Extensions
  pymdownx.betterem:
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  # pymdownx blocks
  pymdownx.blocks.admonition:
    types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      # Custom types
      - info
      - check
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True

  admonition:
  pymdownx.details:
  # Other extensions
  mdx_include:
  markdown_include_variants:


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pysashapy/fasttower
